import { EmojiItem } from '../types';

export const EMOJI_CATEGORIES = [
  { id: 'smileys', name: 'Smileys & Emotion', icon: '😀' },
  { id: 'people', name: 'People & Body', icon: '👋' },
  { id: 'animals', name: 'Animals & Nature', icon: '🦊' },
  { id: 'food', name: 'Food & Drink', icon: '🍕' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'travel', name: 'Travel & Places', icon: '🚀' },
  { id: 'objects', name: 'Objects', icon: '💡' },
  { id: 'symbols', name: 'Symbols', icon: '❤️' },
  { id: 'flags', name: 'Flags', icon: '🏁' },
];

export const SKIN_TONES = [
  { label: 'Default', code: '' },
  { label: 'Light', code: '🏻' },
  { label: 'Medium-Light', code: '🏼' },
  { label: 'Medium', code: '🏽' },
  { label: 'Medium-Dark', code: '🏾' },
  { label: 'Dark', code: '🏿' },
];

export const ALL_EMOJIS: EmojiItem[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'Grinning Face', category: 'smileys', keywords: ['happy', 'smile', 'joy', 'grin'] },
  { emoji: '😃', name: 'Smiling Face with Big Eyes', category: 'smileys', keywords: ['happy', 'excited', 'cheer'] },
  { emoji: '😄', name: 'Grinning Face with Smiling Eyes', category: 'smileys', keywords: ['laugh', 'pleased'] },
  { emoji: '😁', name: 'Beaming Face with Smiling Eyes', category: 'smileys', keywords: ['teeth', 'proud'] },
  { emoji: '😆', name: 'Grinning Squinting Face', category: 'smileys', keywords: ['lol', 'haha', 'rofl'] },
  { emoji: '😅', name: 'Grinning Face with Sweat', category: 'smileys', keywords: ['phew', 'relief', 'nervous'] },
  { emoji: '🤣', name: 'Rolling on the Floor Laughing', category: 'smileys', keywords: ['rofl', 'hilarious'] },
  { emoji: '😂', name: 'Face with Tears of Joy', category: 'smileys', keywords: ['crying laugh', 'funny'] },
  { emoji: '🙂', name: 'Slightly Smiling Face', category: 'smileys', keywords: ['content', 'mild', 'nice'] },
  { emoji: '🙃', name: 'Upside-Down Face', category: 'smileys', keywords: ['sarcasm', 'goofy', 'irony'] },
  { emoji: '😉', name: 'Winking Face', category: 'smileys', keywords: ['wink', 'flirt', 'joke'] },
  { emoji: '😊', name: 'Smiling Face with Smiling Eyes', category: 'smileys', keywords: ['blush', 'warm', 'sweet'] },
  { emoji: '😇', name: 'Smiling Face with Halo', category: 'smileys', keywords: ['angel', 'innocent', 'good'] },
  { emoji: '🥰', name: 'Smiling Face with Hearts', category: 'smileys', keywords: ['in love', 'adore', 'fond'] },
  { emoji: '😍', name: 'Heart Eyes', category: 'smileys', keywords: ['love', 'crush', 'gorgeous'] },
  { emoji: '🤩', name: 'Star-Struck', category: 'smileys', keywords: ['stars', 'amazed', 'wow'] },
  { emoji: '😘', name: 'Face Blowing a Kiss', category: 'smileys', keywords: ['kiss', 'bye', 'affection'] },
  { emoji: '😋', name: 'Face Savoring Food', category: 'smileys', keywords: ['yum', 'delicious', 'tasty'] },
  { emoji: '😛', name: 'Face with Tongue', category: 'smileys', keywords: ['playful', 'silly', 'tongue'] },
  { emoji: '😜', name: 'Winking Face with Tongue', category: 'smileys', keywords: ['crazy', 'wacky', 'party'] },
  { emoji: '🤪', name: 'Zany Face', category: 'smileys', keywords: ['wild', 'kooky', 'derp'] },
  { emoji: '😝', name: 'Squinting Face with Tongue', category: 'smileys', keywords: ['bleh', 'cheeky'] },
  { emoji: '🤑', name: 'Money-Mouth Face', category: 'smileys', keywords: ['rich', 'dollar', 'cash'] },
  { emoji: '🤗', name: 'Hugging Face', category: 'smileys', keywords: ['hug', 'open hands', 'warm'] },
  { emoji: '🤭', name: 'Face with Hand Over Mouth', category: 'smileys', keywords: ['giggle', 'oops', 'secret'] },
  { emoji: '🤫', name: 'Shushing Face', category: 'smileys', keywords: ['quiet', 'hush', 'silence'] },
  { emoji: '🤔', name: 'Thinking Face', category: 'smileys', keywords: ['ponder', 'hmm', 'curious', 'doubt'] },
  { emoji: '🤐', name: 'Zipper-Mouth Face', category: 'smileys', keywords: ['secret', 'sealed', 'quiet'] },
  { emoji: '🤨', name: 'Face with Raised Eyebrow', category: 'smileys', keywords: ['skeptical', 'suspicious'] },
  { emoji: '😐', name: 'Neutral Face', category: 'smileys', keywords: ['poker face', 'blank', 'meh'] },
  { emoji: '😑', name: 'Expressionless Face', category: 'smileys', keywords: ['deadpan', 'unimpressed'] },
  { emoji: '😶', name: 'Face Without Mouth', category: 'smileys', keywords: ['mute', 'speechless'] },
  { emoji: '😏', name: 'Smirking Face', category: 'smileys', keywords: ['smug', 'clever', 'scheming'] },
  { emoji: '😒', name: 'Unamused Face', category: 'smileys', keywords: ['annoyed', 'grumpy', 'sigh'] },
  { emoji: '🙄', name: 'Face with Rolling Eyes', category: 'smileys', keywords: ['eye roll', 'whatever', 'bored'] },
  { emoji: '😬', name: 'Grimacing Face', category: 'smileys', keywords: ['awkward', 'cringe', 'eek'] },
  { emoji: '🤥', name: 'Lying Face', category: 'smileys', keywords: ['pinocchio', 'lie', 'fake'] },
  { emoji: '😌', name: 'Relieved Face', category: 'smileys', keywords: ['calm', 'peaceful', 'zen'] },
  { emoji: '😔', name: 'Pensive Face', category: 'smileys', keywords: ['sad', 'regret', 'down'] },
  { emoji: '😪', name: 'Sleepy Face', category: 'smileys', keywords: ['tired', 'drool', 'nap'] },
  { emoji: '🤤', name: 'Drooling Face', category: 'smileys', keywords: ['craving', 'drool', 'hungry'] },
  { emoji: '😴', name: 'Sleeping Face', category: 'smileys', keywords: ['zzz', 'asleep', 'bed'] },
  { emoji: '😷', name: 'Face with Medical Mask', category: 'smileys', keywords: ['sick', 'mask', 'doctor'] },
  { emoji: '🤒', name: 'Face with Thermometer', category: 'smileys', keywords: ['fever', 'ill', 'flu'] },
  { emoji: '🤕', name: 'Face with Head-Bandage', category: 'smileys', keywords: ['hurt', 'injured', 'ouch'] },
  { emoji: '🤢', name: 'Nauseated Face', category: 'smileys', keywords: ['gross', 'disgust', 'vomit'] },
  { emoji: '🤮', name: 'Face Vomiting', category: 'smileys', keywords: ['puke', 'barf', 'sick'] },
  { emoji: '🤧', name: 'Sneezing Face', category: 'smileys', keywords: ['achoo', 'tissue', 'cold'] },
  { emoji: '🥵', name: 'Hot Face', category: 'smileys', keywords: ['heat', 'summer', 'sweat'] },
  { emoji: '🥶', name: 'Cold Face', category: 'smileys', keywords: ['freezing', 'winter', 'ice'] },
  { emoji: '🥴', name: 'Woozy Face', category: 'smileys', keywords: ['dizzy', 'tipsy', 'confused'] },
  { emoji: '😵', name: 'Knocked-Out Face', category: 'smileys', keywords: ['ko', 'dead', 'passed out'] },
  { emoji: '🤯', name: 'Exploding Head', category: 'smileys', keywords: ['mind blown', 'shocked', 'brain'] },
  { emoji: '🤠', name: 'Cowboy Hat Face', category: 'smileys', keywords: ['western', 'howdy', 'sheriff'] },
  { emoji: '🥳', name: 'Partying Face', category: 'smileys', keywords: ['celebrate', 'birthday', 'horn'] },
  { emoji: '😎', name: 'Smiling Face with Sunglasses', category: 'smileys', keywords: ['cool', 'shades', 'chill'] },
  { emoji: '🤓', name: 'Nerd Face', category: 'smileys', keywords: ['geek', 'glasses', 'study'] },
  { emoji: '🧐', name: 'Face with Monocle', category: 'smileys', keywords: ['curious', 'investigate', 'hmm'] },
  { emoji: '😕', name: 'Confused Face', category: 'smileys', keywords: ['puzzled', 'unsure', 'lost'] },
  { emoji: '😟', name: 'Worried Face', category: 'smileys', keywords: ['anxious', 'concerned'] },
  { emoji: '🙁', name: 'Slightly Frowning Face', category: 'smileys', keywords: ['sad', 'disappointed'] },
  { emoji: '😮', name: 'Face with Open Mouth', category: 'smileys', keywords: ['surprise', 'gasp', 'whoa'] },
  { emoji: '😯', name: 'Hushed Face', category: 'smileys', keywords: ['stunned', 'silent', 'omg'] },
  { emoji: '😲', name: 'Astonished Face', category: 'smileys', keywords: ['amazed', 'shocked', 'gasp'] },
  { emoji: '😳', name: 'Flushed Face', category: 'smileys', keywords: ['embarrassed', 'blushing', 'nervous'] },
  { emoji: '🥺', name: 'Pleading Face', category: 'smileys', keywords: ['puppy eyes', 'begging', 'cute'] },
  { emoji: '😦', name: 'Frowning Face with Open Mouth', category: 'smileys', keywords: ['scared', 'appalled'] },
  { emoji: '😨', name: 'Fearful Face', category: 'smileys', keywords: ['frightened', 'spooked'] },
  { emoji: '😰', name: 'Anxious Face with Sweat', category: 'smileys', keywords: ['stressed', 'worried'] },
  { emoji: '😥', name: 'Sad but Relieved Face', category: 'smileys', keywords: ['almost', 'sigh'] },
  { emoji: '😢', name: 'Crying Face', category: 'smileys', keywords: ['tear', 'sad', 'weep'] },
  { emoji: '😭', name: 'Loudly Crying Face', category: 'smileys', keywords: ['bawling', 'sobbing', 'tears'] },
  { emoji: '😱', name: 'Face Screaming in Fear', category: 'smileys', keywords: ['horror', 'scream', 'scared'] },
  { emoji: '😖', name: 'Confounded Face', category: 'smileys', keywords: ['frustrated', 'quivering'] },
  { emoji: '😣', name: 'Persevering Face', category: 'smileys', keywords: ['struggling', 'trying'] },
  { emoji: '😞', name: 'Disappointed Face', category: 'smileys', keywords: ['letdown', 'sad'] },
  { emoji: '😓', name: 'Downcast Face with Sweat', category: 'smileys', keywords: ['hard work', 'exhausted'] },
  { emoji: '😩', name: 'Weary Face', category: 'smileys', keywords: ['tired', 'complaining'] },
  { emoji: '😫', name: 'Tired Face', category: 'smileys', keywords: ['exhausted', 'give up'] },
  { emoji: '🥱', name: 'Yawning Face', category: 'smileys', keywords: ['bored', 'sleepy', 'yawn'] },
  { emoji: '😤', name: 'Face with Steam From Nose', category: 'smileys', keywords: ['determined', 'angry', 'huff'] },
  { emoji: '😡', name: 'Enraged Face', category: 'smileys', keywords: ['mad', 'furious', 'red'] },
  { emoji: '😠', name: 'Angry Face', category: 'smileys', keywords: ['mad', 'cross', 'irritated'] },
  { emoji: '🤬', name: 'Face with Symbols on Mouth', category: 'smileys', keywords: ['swearing', 'curse', 'rage'] },
  { emoji: '😈', name: 'Smiling Face with Horns', category: 'smileys', keywords: ['devil', 'mischief', 'evil'] },
  { emoji: '👿', name: 'Angry Face with Horns', category: 'smileys', keywords: ['demon', 'goblin'] },
  { emoji: '💀', name: 'Skull', category: 'smileys', keywords: ['dead', 'skeleton', 'i am dead'] },
  { emoji: '☠️', name: 'Skull and Crossbones', category: 'smileys', keywords: ['pirate', 'danger', 'poison'] },
  { emoji: '💩', name: 'Pile of Poo', category: 'smileys', keywords: ['poop', 'funny', 'turd'] },
  { emoji: '🤡', name: 'Clown Face', category: 'smileys', keywords: ['circus', 'fool', 'joker'] },
  { emoji: '👹', name: 'Ogre', category: 'smileys', keywords: ['monster', 'mask', 'japanese'] },
  { emoji: '👻', name: 'Ghost', category: 'smileys', keywords: ['spooky', 'halloween', 'boo'] },
  { emoji: '👽', name: 'Alien', category: 'smileys', keywords: ['ufo', 'et', 'space'] },
  { emoji: '🤖', name: 'Robot', category: 'smileys', keywords: ['bot', 'ai', 'cyborg', 'machine'] },

  // People & Body (Gestures & Hands)
  { emoji: '👋', name: 'Waving Hand', category: 'people', keywords: ['hello', 'bye', 'wave', 'hi'] },
  { emoji: '🤚', name: 'Raised Back of Hand', category: 'people', keywords: ['stop', 'high five', 'hand'] },
  { emoji: '🖐️', name: 'Hand with Fingers Splayed', category: 'people', keywords: ['five', 'open'] },
  { emoji: '✋', name: 'Raised Hand', category: 'people', keywords: ['high five', 'stop', 'raise hand', 'halt'] },
  { emoji: '🖖', name: 'Vulcan Salute', category: 'people', keywords: ['spock', 'star trek', 'live long'] },
  { emoji: '👌', name: 'OK Hand', category: 'people', keywords: ['okay', 'perfect', 'nice', 'correct'] },
  { emoji: '🤌', name: 'Pinched Fingers', category: 'people', keywords: ['italian', 'gesture', 'what'] },
  { emoji: '🤏', name: 'Pinching Hand', category: 'people', keywords: ['small', 'little', 'tiny'] },
  { emoji: '✌️', name: 'Victory Hand', category: 'people', keywords: ['peace', 'two', 'v sign', 'victory'] },
  { emoji: '🤞', name: 'Crossed Fingers', category: 'people', keywords: ['luck', 'hope', 'promise', 'fingers crossed'] },
  { emoji: '🫰', name: 'Hand with Index Finger and Thumb Crossed', category: 'people', keywords: ['finger heart', 'kpop', 'saranghae', 'love', 'snap'] },
  { emoji: '🤟', name: 'Love-You Gesture', category: 'people', keywords: ['ily', 'rock', 'love you', 'asl'] },
  { emoji: '🤘', name: 'Sign of the Horns', category: 'people', keywords: ['rock on', 'metal', 'horns'] },
  { emoji: '🤙', name: 'Call Me Hand', category: 'people', keywords: ['shaka', 'hang loose', 'phone'] },
  { emoji: '👈', name: 'Backhand Index Pointing Left', category: 'people', keywords: ['point', 'left', 'direction'] },
  { emoji: '👉', name: 'Backhand Index Pointing Right', category: 'people', keywords: ['point', 'right', 'there'] },
  { emoji: '👆', name: 'Backhand Index Pointing Up', category: 'people', keywords: ['up', 'above', 'point'] },
  { emoji: '🖕', name: 'Middle Finger', category: 'people', keywords: ['rude'] },
  { emoji: '👇', name: 'Backhand Index Pointing Down', category: 'people', keywords: ['down', 'below'] },
  { emoji: '☝️', name: 'Index Pointing Up', category: 'people', keywords: ['one', 'first', 'point', 'idea', 'attention'] },
  { emoji: '👍', name: 'Thumbs Up', category: 'people', keywords: ['yes', 'like', 'approve', 'good', 'agree', 'thumbs up'] },
  { emoji: '👎', name: 'Thumbs Down', category: 'people', keywords: ['no', 'dislike', 'bad', 'disapprove', 'thumbs down'] },
  { emoji: '✊', name: 'Raised Fist', category: 'people', keywords: ['fist', 'power', 'solidarity', 'stone', 'rock'] },
  { emoji: '👊', name: 'Oncoming Fist', category: 'people', keywords: ['brofist', 'punch', 'bump'] },
  { emoji: '🤛', name: 'Left-Facing Fist', category: 'people', keywords: ['fist bump'] },
  { emoji: '🤜', name: 'Right-Facing Fist', category: 'people', keywords: ['fist bump'] },
  { emoji: '👏', name: 'Clapping Hands', category: 'people', keywords: ['applause', 'praise', 'bravo', 'clap'] },
  { emoji: '🙌', name: 'Raising Hands', category: 'people', keywords: ['hooray', 'celebrate', 'praise', 'woo'] },
  { emoji: '👐', name: 'Open Hands', category: 'people', keywords: ['welcome', 'hug', 'hands'] },
  { emoji: '🤲', name: 'Palms Up Together', category: 'people', keywords: ['prayer', 'cupped', 'hope'] },
  { emoji: '🤝', name: 'Handshake', category: 'people', keywords: ['deal', 'agreement', 'partner', 'meet'] },
  { emoji: '🙏', name: 'Folded Hands', category: 'people', keywords: ['please', 'thank you', 'namaste', 'pray'] },
  { emoji: '✍️', name: 'Writing Hand', category: 'people', keywords: ['write', 'pen', 'draw'] },
  { emoji: '💅', name: 'Nail Polish', category: 'people', keywords: ['glam', 'sassy', 'slay'] },
  { emoji: '🤳', name: 'Selfie', category: 'people', keywords: ['camera', 'phone', 'photo'] },
  { emoji: '💪', name: 'Flexed Biceps', category: 'people', keywords: ['strong', 'muscle', 'workout', 'power'] },
  { emoji: '🦾', name: 'Mechanical Arm', category: 'people', keywords: ['prosthetic', 'cyborg', 'robot arm'] },
  { emoji: '🦿', name: 'Mechanical Leg', category: 'people', keywords: ['prosthetic', 'robot leg'] },
  { emoji: '🦵', name: 'Leg', category: 'people', keywords: ['kick', 'limb'] },
  { emoji: '🦶', name: 'Foot', category: 'people', keywords: ['step', 'walk', 'toe'] },
  { emoji: '👂', name: 'Ear', category: 'people', keywords: ['listen', 'hear', 'sound'] },
  { emoji: '👃', name: 'Nose', category: 'people', keywords: ['smell', 'sniff'] },
  { emoji: '🧠', name: 'Brain', category: 'people', keywords: ['smart', 'think', 'mind', 'intellect'] },
  { emoji: '🫀', name: 'Anatomical Heart', category: 'people', keywords: ['cardiology', 'organ'] },
  { emoji: '👀', name: 'Eyes', category: 'people', keywords: ['look', 'see', 'peek', 'shifty'] },
  { emoji: '👁️', name: 'Eye', category: 'people', keywords: ['vision', 'watch'] },
  { emoji: '👅', name: 'Tongue', category: 'people', keywords: ['taste', 'lick'] },
  { emoji: '👄', name: 'Mouth', category: 'people', keywords: ['lips', 'kiss', 'talk'] },

  // Animals & Nature
  { emoji: '🐶', name: 'Dog Face', category: 'animals', keywords: ['puppy', 'pet', 'canine'] },
  { emoji: '🐱', name: 'Cat Face', category: 'animals', keywords: ['kitten', 'meow', 'feline'] },
  { emoji: '🐭', name: 'Mouse Face', category: 'animals', keywords: ['rodent', 'cheese'] },
  { emoji: '🐹', name: 'Hamster Face', category: 'animals', keywords: ['pet', 'cute', 'fluffy'] },
  { emoji: '🐰', name: 'Rabbit Face', category: 'animals', keywords: ['bunny', 'easter', 'hops'] },
  { emoji: '🦊', name: 'Fox Face', category: 'animals', keywords: ['clever', 'wild'] },
  { emoji: '🐻', name: 'Bear Face', category: 'animals', keywords: ['grizzly', 'teddy'] },
  { emoji: '🐼', name: 'Panda Face', category: 'animals', keywords: ['bamboo', 'cute'] },
  { emoji: '🐨', name: 'Koala', category: 'animals', keywords: ['australia', 'eucalyptus'] },
  { emoji: '🐯', name: 'Tiger Face', category: 'animals', keywords: ['stripes', 'wild', 'cat'] },
  { emoji: '🦁', name: 'Lion Face', category: 'animals', keywords: ['king', 'mane', 'safari'] },
  { emoji: '🐮', name: 'Cow Face', category: 'animals', keywords: ['moo', 'milk', 'farm'] },
  { emoji: '🐷', name: 'Pig Face', category: 'animals', keywords: ['oink', 'farm', 'pink'] },
  { emoji: '🐸', name: 'Frog Face', category: 'animals', keywords: ['toad', 'hop', 'ribbit'] },
  { emoji: '🐵', name: 'Monkey Face', category: 'animals', keywords: ['banana', 'jungle', 'ape'] },
  { emoji: '🐔', name: 'Chicken', category: 'animals', keywords: ['rooster', 'bird', 'farm'] },
  { emoji: '🐧', name: 'Penguin', category: 'animals', keywords: ['antarctica', 'ice', 'bird'] },
  { emoji: '🐦', name: 'Bird', category: 'animals', keywords: ['tweet', 'fly', 'feather'] },
  { emoji: '🐤', name: 'Baby Chick', category: 'animals', keywords: ['cute', 'yellow', 'hatch'] },
  { emoji: '🦆', name: 'Duck', category: 'animals', keywords: ['quack', 'pond'] },
  { emoji: '🦅', name: 'Eagle', category: 'animals', keywords: ['raptor', 'bird of prey', 'america'] },
  { emoji: '🦉', name: 'Owl', category: 'animals', keywords: ['wise', 'night', 'hoot'] },
  { emoji: '🦇', name: 'Bat', category: 'animals', keywords: ['vampire', 'cave', 'spooky'] },
  { emoji: '🐺', name: 'Wolf', category: 'animals', keywords: ['howl', 'pack', 'moon'] },
  { emoji: '🦄', name: 'Unicorn', category: 'animals', keywords: ['magic', 'fantasy', 'rainbow'] },
  { emoji: '🐝', name: 'Honeybee', category: 'animals', keywords: ['buzz', 'honey', 'flower'] },
  { emoji: '🐛', name: 'Bug', category: 'animals', keywords: ['caterpillar', 'insect'] },
  { emoji: '🦋', name: 'Butterfly', category: 'animals', keywords: ['wings', 'nature', 'pretty'] },
  { emoji: '🐌', name: 'Snail', category: 'animals', keywords: ['slow', 'shell'] },
  { emoji: '🐞', name: 'Lady Beetle', category: 'animals', keywords: ['ladybug', 'spots'] },
  { emoji: '🐜', name: 'Ant', category: 'animals', keywords: ['colony', 'small', 'strong'] },
  { emoji: '🐢', name: 'Turtle', category: 'animals', keywords: ['tortoise', 'shell', 'slow'] },
  { emoji: '🐍', name: 'Snake', category: 'animals', keywords: ['reptile', 'serpent', 'hiss'] },
  { emoji: '🐙', name: 'Octopus', category: 'animals', keywords: ['tentacles', 'ocean', 'sea'] },
  { emoji: '🦑', name: 'Squid', category: 'animals', keywords: ['calamari', 'sea creature'] },
  { emoji: '🦐', name: 'Shrimp', category: 'animals', keywords: ['prawn', 'seafood'] },
  { emoji: '🦞', name: 'Lobster', category: 'animals', keywords: ['crustacean', 'claws'] },
  { emoji: '🦀', name: 'Crab', category: 'animals', keywords: ['beach', 'pincers'] },
  { emoji: '🐡', name: 'Blowfish', category: 'animals', keywords: ['puffer', 'spike'] },
  { emoji: '🐠', name: 'Tropical Fish', category: 'animals', keywords: ['reef', 'nemo', 'swim'] },
  { emoji: '🐟', name: 'Fish', category: 'animals', keywords: ['water', 'swimming'] },
  { emoji: '🐬', name: 'Dolphin', category: 'animals', keywords: ['clever', 'marine', 'sea'] },
  { emoji: '🐳', name: 'Spouting Whale', category: 'animals', keywords: ['ocean', 'huge', 'blowhole'] },
  { emoji: '🦈', name: 'Shark', category: 'animals', keywords: ['jaws', 'predator', 'ocean'] },
  { emoji: '🐊', name: 'Crocodile', category: 'animals', keywords: ['alligator', 'swamp'] },
  { emoji: '🐅', name: 'Leopard', category: 'animals', keywords: ['fast', 'spots'] },
  { emoji: '🦓', name: 'Zebra', category: 'animals', keywords: ['stripes', 'safari'] },
  { emoji: '🐘', name: 'Elephant', category: 'animals', keywords: ['trunk', 'tusks', 'huge'] },
  { emoji: '🦏', name: 'Rhinoceros', category: 'animals', keywords: ['horn', 'safari'] },
  { emoji: '🦛', name: 'Hippopotamus', category: 'animals', keywords: ['hippo', 'river'] },
  { emoji: '🦒', name: 'Giraffe', category: 'animals', keywords: ['tall', 'neck', 'safari'] },
  { emoji: '🌲', name: 'Evergreen Tree', category: 'animals', keywords: ['pine', 'forest', 'wood'] },
  { emoji: '🌳', name: 'Deciduous Tree', category: 'animals', keywords: ['nature', 'leaves', 'park'] },
  { emoji: '🌴', name: 'Palm Tree', category: 'animals', keywords: ['beach', 'tropical', 'vacation'] },
  { emoji: '🌵', name: 'Cactus', category: 'animals', keywords: ['desert', 'spiky'] },
  { emoji: '🌸', name: 'Cherry Blossom', category: 'animals', keywords: ['sakura', 'pink', 'spring', 'flower', 'phool'] },
  { emoji: '🪷', name: 'Lotus Flower', category: 'animals', keywords: ['lotus', 'kamal', 'padma', 'sacred', 'flower', 'zen', 'india'] },
  { emoji: '🌹', name: 'Rose', category: 'animals', keywords: ['flower', 'red', 'romance', 'rose', 'gulab'] },
  { emoji: '🌺', name: 'Hibiscus', category: 'animals', keywords: ['hibiscus', 'flower', 'tropical', 'red', 'gudhal'] },
  { emoji: '🌻', name: 'Sunflower', category: 'animals', keywords: ['yellow', 'summer', 'sun', 'flower', 'surajmukhi'] },
  { emoji: '🌼', name: 'Blossom / Daisy', category: 'animals', keywords: ['daisy', 'yellow', 'flower', 'white', 'chamomile'] },
  { emoji: '🌷', name: 'Tulip', category: 'animals', keywords: ['tulip', 'spring', 'flower', 'pink', 'netherlands'] },
  { emoji: '💐', name: 'Bouquet', category: 'animals', keywords: ['bouquet', 'flowers', 'gift', 'bunch', 'love'] },
  { emoji: '💮', name: 'White Flower', category: 'animals', keywords: ['white', 'flower', 'stamp', 'cherry'] },
  { emoji: '🏵️', name: 'Rosette', category: 'animals', keywords: ['rosette', 'flower', 'decoration'] },
  { emoji: '🥀', name: 'Wilted Flower', category: 'animals', keywords: ['wilted', 'rose', 'droop', 'flower', 'sad'] },
  { emoji: '🌱', name: 'Seedling', category: 'animals', keywords: ['sprout', 'young', 'plant', 'grow'] },
  { emoji: '🌿', name: 'Herb', category: 'animals', keywords: ['leaf', 'green', 'herb', 'plant'] },
  { emoji: '🍀', name: 'Four Leaf Clover', category: 'animals', keywords: ['lucky', 'irish', 'green'] },
  { emoji: '🍁', name: 'Maple Leaf', category: 'animals', keywords: ['autumn', 'fall', 'canada'] },
  { emoji: '🍄', name: 'Mushroom', category: 'animals', keywords: ['fungus', 'toadstool', 'mario'] },

  // Food & Drink
  { emoji: '🍏', name: 'Green Apple', category: 'food', keywords: ['fruit', 'fresh'] },
  { emoji: '🍎', name: 'Red Apple', category: 'food', keywords: ['fruit', 'teacher'] },
  { emoji: '🍐', name: 'Pear', category: 'food', keywords: ['fruit'] },
  { emoji: '🍊', name: 'Tangerine', category: 'food', keywords: ['orange', 'citrus'] },
  { emoji: '🍋', name: 'Lemon', category: 'food', keywords: ['sour', 'citrus'] },
  { emoji: '🍌', name: 'Banana', category: 'food', keywords: ['fruit', 'potassium', 'monkey'] },
  { emoji: '🍉', name: 'Watermelon', category: 'food', keywords: ['summer', 'slice', 'melon'] },
  { emoji: '🍇', name: 'Grapes', category: 'food', keywords: ['wine', 'fruit', 'bunch'] },
  { emoji: '🍓', name: 'Strawberry', category: 'food', keywords: ['berry', 'sweet', 'red'] },
  { emoji: '🫐', name: 'Blueberries', category: 'food', keywords: ['berry', 'fruit'] },
  { emoji: '🍒', name: 'Cherries', category: 'food', keywords: ['fruit', 'pair'] },
  { emoji: '🍑', name: 'Peach', category: 'food', keywords: ['fruit', 'fuzzy'] },
  { emoji: '🍍', name: 'Pineapple', category: 'food', keywords: ['tropical', 'sweet'] },
  { emoji: '🥭', name: 'Mango', category: 'food', keywords: ['tropical', 'juicy'] },
  { emoji: '🥑', name: 'Avocado', category: 'food', keywords: ['guacamole', 'toast'] },
  { emoji: '🥦', name: 'Broccoli', category: 'food', keywords: ['vegetable', 'healthy'] },
  { emoji: '🌽', name: 'Ear of Corn', category: 'food', keywords: ['maize', 'popcorn'] },
  { emoji: '🥕', name: 'Carrot', category: 'food', keywords: ['vegetable', 'rabbit'] },
  { emoji: '🍟', name: 'French Fries', category: 'food', keywords: ['potato', 'fast food'] },
  { emoji: '🍕', name: 'Pizza', category: 'food', keywords: ['slice', 'cheese', 'pepperoni'] },
  { emoji: '🍔', name: 'Hamburger', category: 'food', keywords: ['burger', 'beef', 'fast food'] },
  { emoji: '🌭', name: 'Hot Dog', category: 'food', keywords: ['sausage', 'bun', 'mustard'] },
  { emoji: '🥪', name: 'Sandwich', category: 'food', keywords: ['lunch', 'bread'] },
  { emoji: '🌮', name: 'Taco', category: 'food', keywords: ['mexican', 'shell'] },
  { emoji: '🌯', name: 'Burrito', category: 'food', keywords: ['wrap', 'mexican'] },
  { emoji: '🍜', name: 'Steaming Bowl', category: 'food', keywords: ['ramen', 'noodles', 'soup'] },
  { emoji: '🍝', name: 'Spaghetti', category: 'food', keywords: ['pasta', 'italian'] },
  { emoji: '🍣', name: 'Sushi', category: 'food', keywords: ['japanese', 'fish', 'rice'] },
  { emoji: '🍱', name: 'Bento Box', category: 'food', keywords: ['lunch', 'japanese'] },
  { emoji: '🥟', name: 'Dumpling', category: 'food', keywords: ['dim sum', 'potsticker'] },
  { emoji: '🍦', name: 'Soft Ice Cream', category: 'food', keywords: ['dessert', 'cone'] },
  { emoji: '🍧', name: 'Shaved Ice', category: 'food', keywords: ['dessert', 'sweet'] },
  { emoji: '🍨', name: 'Ice Cream', category: 'food', keywords: ['sundae', 'bowl'] },
  { emoji: '🍩', name: 'Doughnut', category: 'food', keywords: ['donut', 'glaze', 'sprinkles'] },
  { emoji: '🍪', name: 'Cookie', category: 'food', keywords: ['chocolate chip', 'biscuit'] },
  { emoji: '🎂', name: 'Birthday Cake', category: 'food', keywords: ['celebrate', 'candles'] },
  { emoji: '🍰', name: 'Shortcake', category: 'food', keywords: ['pastry', 'slice'] },
  { emoji: '🧁', name: 'Cupcake', category: 'food', keywords: ['frosting', 'sweet'] },
  { emoji: '🍫', name: 'Chocolate Bar', category: 'food', keywords: ['candy', 'cocoa'] },
  { emoji: '🍿', name: 'Popcorn', category: 'food', keywords: ['movie', 'cinema', 'snack'] },
  { emoji: '☕', name: 'Hot Beverage', category: 'food', keywords: ['coffee', 'tea', 'mug', 'morning'] },
  { emoji: '🍵', name: 'Teacup Without Handle', category: 'food', keywords: ['green tea', 'matcha'] },
  { emoji: '🧃', name: 'Beverage Box', category: 'food', keywords: ['juice', 'straw'] },
  { emoji: '🥤', name: 'Cup with Straw', category: 'food', keywords: ['soda', 'drink', 'cola'] },
  { emoji: '🧋', name: 'Bubble Tea', category: 'food', keywords: ['boba', 'milk tea'] },

  // Activities
  { emoji: '⚽', name: 'Soccer Ball', category: 'activities', keywords: ['football', 'fifa', 'sport'] },
  { emoji: '🏀', name: 'Basketball', category: 'activities', keywords: ['nba', 'hoop', 'sport'] },
  { emoji: '🏈', name: 'American Football', category: 'activities', keywords: ['nfl', 'touchdown'] },
  { emoji: '⚾', name: 'Baseball', category: 'activities', keywords: ['mlb', 'home run'] },
  { emoji: '🎾', name: 'Tennis', category: 'activities', keywords: ['racket', 'court', 'ball'] },
  { emoji: '🏐', name: 'Volleyball', category: 'activities', keywords: ['beach', 'spike'] },
  { emoji: '🏓', name: 'Ping Pong', category: 'activities', keywords: ['table tennis', 'paddle'] },
  { emoji: '🏸', name: 'Badminton', category: 'activities', keywords: ['shuttlecock'] },
  { emoji: '🥊', name: 'Boxing Glove', category: 'activities', keywords: ['fight', 'punch'] },
  { emoji: '🥋', name: 'Martial Arts Uniform', category: 'activities', keywords: ['karate', 'judo', 'dojo'] },
  { emoji: '🎯', name: 'Bullseye', category: 'activities', keywords: ['darts', 'target', 'goal'] },
  { emoji: '🎮', name: 'Video Game', category: 'activities', keywords: ['controller', 'playstation', 'xbox', 'gaming'] },
  { emoji: '🕹️', name: 'Joystick', category: 'activities', keywords: ['arcade', 'retro'] },
  { emoji: '🎲', name: 'Game Die', category: 'activities', keywords: ['dice', 'board game', 'roll'] },
  { emoji: '♟️', name: 'Chess Pawn', category: 'activities', keywords: ['strategy', 'checkmate'] },
  { emoji: '🎨', name: 'Artist Palette', category: 'activities', keywords: ['art', 'paint', 'draw'] },
  { emoji: '🎭', name: 'Performing Arts', category: 'activities', keywords: ['theater', 'drama', 'acting'] },
  { emoji: '🎪', name: 'Circus Tent', category: 'activities', keywords: ['carnival', 'show'] },
  { emoji: '🎤', name: 'Microphone', category: 'activities', keywords: ['sing', 'karaoke', 'voice'] },
  { emoji: '🎧', name: 'Headphone', category: 'activities', keywords: ['music', 'listen', 'audio'] },
  { emoji: '🎸', name: 'Guitar', category: 'activities', keywords: ['rock', 'strings', 'music'] },
  { emoji: '🎹', name: 'Musical Keyboard', category: 'activities', keywords: ['piano', 'keys'] },
  { emoji: '🥁', name: 'Drum', category: 'activities', keywords: ['beat', 'rhythm'] },
  { emoji: '🏆', name: 'Trophy', category: 'activities', keywords: ['champion', 'winner', 'cup', 'first'] },
  { emoji: '🥇', name: '1st Place Medal', category: 'activities', keywords: ['gold', 'first', 'victory'] },
  { emoji: '🥈', name: '2nd Place Medal', category: 'activities', keywords: ['silver', 'second'] },
  { emoji: '🥉', name: '3rd Place Medal', category: 'activities', keywords: ['bronze', 'third'] },

  // Travel & Places
  { emoji: '🚗', name: 'Automobile', category: 'travel', keywords: ['car', 'drive', 'vehicle'] },
  { emoji: '🚕', name: 'Taxi', category: 'travel', keywords: ['cab', 'uber'] },
  { emoji: '🏎️', name: 'Racing Car', category: 'travel', keywords: ['f1', 'speed'] },
  { emoji: '🚲', name: 'Bicycle', category: 'travel', keywords: ['bike', 'cycle', 'pedal'] },
  { emoji: '🛴', name: 'Kick Scooter', category: 'travel', keywords: ['scooter'] },
  { emoji: '🛵', name: 'Motor Scooter', category: 'travel', keywords: ['vespa', 'moped'] },
  { emoji: '🏍️', name: 'Motorcycle', category: 'travel', keywords: ['bike', 'chopper'] },
  { emoji: '✈️', name: 'Airplane', category: 'travel', keywords: ['flight', 'travel', 'vacation'] },
  { emoji: '🚀', name: 'Rocket', category: 'travel', keywords: ['space', 'launch', 'blast off', 'moon'] },
  { emoji: '🛸', name: 'Flying Saucer', category: 'travel', keywords: ['alien', 'ufo'] },
  { emoji: '🚁', name: 'Helicopter', category: 'travel', keywords: ['chopper', 'rotor'] },
  { emoji: '⛵', name: 'Sailboat', category: 'travel', keywords: ['boat', 'yacht', 'sea'] },
  { emoji: '🚢', name: 'Ship', category: 'travel', keywords: ['cruise', 'ocean'] },
  { emoji: '🚂', name: 'Locomotive', category: 'travel', keywords: ['train', 'steam'] },
  { emoji: '🚄', name: 'High-Speed Train', category: 'travel', keywords: ['bullet train', 'rail'] },
  { emoji: '🗽', name: 'Statue of Liberty', category: 'travel', keywords: ['new york', 'usa'] },
  { emoji: '🗼', name: 'Tokyo Tower', category: 'travel', keywords: ['japan', 'landmark'] },
  { emoji: '🏰', name: 'Castle', category: 'travel', keywords: ['fairytale', 'palace'] },
  { emoji: '🎡', name: 'Ferris Wheel', category: 'travel', keywords: ['amusement park', 'fair'] },
  { emoji: '🎢', name: 'Roller Coaster', category: 'travel', keywords: ['theme park', 'thrill'] },
  { emoji: '🏖️', name: 'Beach with Umbrella', category: 'travel', keywords: ['sand', 'sea', 'summer'] },
  { emoji: '🏝️', name: 'Desert Island', category: 'travel', keywords: ['tropical', 'paradise'] },
  { emoji: '🌋', name: 'Volcano', category: 'travel', keywords: ['lava', 'eruption'] },
  { emoji: '🏕️', name: 'Camping', category: 'travel', keywords: ['tent', 'outdoors'] },

  // Objects
  { emoji: '💡', name: 'Light Bulb', category: 'objects', keywords: ['idea', 'bright', 'smart', 'invention'] },
  { emoji: '🔦', name: 'Flashlight', category: 'objects', keywords: ['torch', 'light'] },
  { emoji: '💻', name: 'Laptop', category: 'objects', keywords: ['computer', 'pc', 'macbook', 'work'] },
  { emoji: '🖥️', name: 'Desktop Computer', category: 'objects', keywords: ['monitor', 'screen'] },
  { emoji: '📱', name: 'Mobile Phone', category: 'objects', keywords: ['smartphone', 'iphone', 'cell'] },
  { emoji: '☎️', name: 'Telephone', category: 'objects', keywords: ['call', 'ring'] },
  { emoji: '📷', name: 'Camera', category: 'objects', keywords: ['photo', 'picture', 'snapshot'] },
  { emoji: '📹', name: 'Video Camera', category: 'objects', keywords: ['record', 'movie', 'film'] },
  { emoji: '📺', name: 'Television', category: 'objects', keywords: ['tv', 'shows'] },
  { emoji: '📻', name: 'Radio', category: 'objects', keywords: ['fm', 'am', 'broadcast'] },
  { emoji: '⏰', name: 'Alarm Clock', category: 'objects', keywords: ['wake up', 'time', 'morning'] },
  { emoji: '⏳', name: 'Hourglass Not Done', category: 'objects', keywords: ['timer', 'sand', 'wait'] },
  { emoji: '🔋', name: 'Battery', category: 'objects', keywords: ['power', 'charge'] },
  { emoji: '🔌', name: 'Electric Plug', category: 'objects', keywords: ['cable', 'power'] },
  { emoji: '🔍', name: 'Magnifying Glass Tilt Left', category: 'objects', keywords: ['search', 'find', 'zoom'] },
  { emoji: '🔒', name: 'Locked', category: 'objects', keywords: ['security', 'password', 'private'] },
  { emoji: '🔓', name: 'Unlocked', category: 'objects', keywords: ['open', 'access'] },
  { emoji: '🔑', name: 'Key', category: 'objects', keywords: ['lock', 'door', 'clue'] },
  { emoji: '🔨', name: 'Hammer', category: 'objects', keywords: ['tool', 'build', 'fix'] },
  { emoji: '🪛', name: 'Screwdriver', category: 'objects', keywords: ['tool', 'repair'] },
  { emoji: '🧲', name: 'Magnet', category: 'objects', keywords: ['attract', 'physics'] },
  { emoji: '🧪', name: 'Test Tube', category: 'objects', keywords: ['science', 'chemistry', 'lab', 'experiment'] },
  { emoji: '🧬', name: 'DNA', category: 'objects', keywords: ['genetics', 'biology', 'science'] },
  { emoji: '🔬', name: 'Microscope', category: 'objects', keywords: ['lab', 'biology', 'cells'] },
  { emoji: '🔭', name: 'Telescope', category: 'objects', keywords: ['astronomy', 'stars', 'space'] },
  { emoji: '📡', name: 'Satellite Antenna', category: 'objects', keywords: ['signal', 'radar'] },
  { emoji: '📚', name: 'Books', category: 'objects', keywords: ['library', 'reading', 'study', 'school'] },
  { emoji: '✏️', name: 'Pencil', category: 'objects', keywords: ['write', 'sketch'] },
  { emoji: '🎉', name: 'Party Popper', category: 'objects', keywords: ['celebrate', 'confetti', 'woohoo'] },
  { emoji: '🎁', name: 'Wrapped Gift', category: 'objects', keywords: ['present', 'birthday', 'surprise'] },

  // Symbols
  { emoji: '❤️', name: 'Red Heart', category: 'symbols', keywords: ['love', 'heart', 'like', 'passion'] },
  { emoji: '🧡', name: 'Orange Heart', category: 'symbols', keywords: ['love'] },
  { emoji: '💛', name: 'Yellow Heart', category: 'symbols', keywords: ['friendship', 'warmth'] },
  { emoji: '💚', name: 'Green Heart', category: 'symbols', keywords: ['nature', 'envy'] },
  { emoji: '💙', name: 'Blue Heart', category: 'symbols', keywords: ['trust', 'peace'] },
  { emoji: '💜', name: 'Purple Heart', category: 'symbols', keywords: ['honor', 'bts'] },
  { emoji: '🖤', name: 'Black Heart', category: 'symbols', keywords: ['dark', 'goth'] },
  { emoji: '🤍', name: 'White Heart', category: 'symbols', keywords: ['pure', 'clean'] },
  { emoji: '🤎', name: 'Brown Heart', category: 'symbols', keywords: ['earth'] },
  { emoji: '💔', name: 'Broken Heart', category: 'symbols', keywords: ['heartbreak', 'sad', 'breakup'] },
  { emoji: '💖', name: 'Sparkling Heart', category: 'symbols', keywords: ['shine', 'love'] },
  { emoji: '💗', name: 'Growing Heart', category: 'symbols', keywords: ['pulse', 'love'] },
  { emoji: '💓', name: 'Beating Heart', category: 'symbols', keywords: ['heartbeat', 'thump'] },
  { emoji: '💞', name: 'Revolving Hearts', category: 'symbols', keywords: ['affection', 'romance'] },
  { emoji: '💕', name: 'Two Hearts', category: 'symbols', keywords: ['love in the air'] },
  { emoji: '✨', name: 'Sparkles', category: 'symbols', keywords: ['magic', 'shine', 'glitter', 'ai', 'clean'] },
  { emoji: '⭐', name: 'Star', category: 'symbols', keywords: ['rating', 'favorite'] },
  { emoji: '🌟', name: 'Glowing Star', category: 'symbols', keywords: ['superstar', 'bright'] },
  { emoji: '🔥', name: 'Fire', category: 'symbols', keywords: ['lit', 'hot', 'flame', 'streak'] },
  { emoji: '⚡', name: 'High Voltage', category: 'symbols', keywords: ['lightning', 'fast', 'electric', 'power'] },
  { emoji: '💥', name: 'Collision', category: 'symbols', keywords: ['boom', 'blast', 'bang'] },
  { emoji: '💯', name: 'Hundred Points', category: 'symbols', keywords: ['perfect', 'score', 'keep it real'] },
  { emoji: '✅', name: 'Check Mark Button', category: 'symbols', keywords: ['yes', 'correct', 'done'] },
  { emoji: '❌', name: 'Cross Mark', category: 'symbols', keywords: ['no', 'wrong', 'cancel'] },
  { emoji: '❓', name: 'Question Mark', category: 'symbols', keywords: ['confused', 'help', 'what'] },
  { emoji: '❗', name: 'Exclamation Mark', category: 'symbols', keywords: ['warning', 'alert', 'important'] },
  { emoji: '💤', name: 'Zzz', category: 'symbols', keywords: ['sleeping', 'tired', 'dream'] },
  { emoji: '🎵', name: 'Musical Note', category: 'symbols', keywords: ['song', 'music'] },
  { emoji: '🎶', name: 'Musical Notes', category: 'symbols', keywords: ['tune', 'melody'] },

  // Flags
  { emoji: '🏁', name: 'Chequered Flag', category: 'flags', keywords: ['race', 'finish', 'start'] },
  { emoji: '🚩', name: 'Triangular Flag', category: 'flags', keywords: ['post', 'red flag'] },
  { emoji: '🎌', name: 'Crossed Flags', category: 'flags', keywords: ['japan', 'holiday'] },
  { emoji: '🏴‍☠️', name: 'Pirate Flag', category: 'flags', keywords: ['jolly roger', 'skull'] },
  { emoji: '🏳️‍🌈', name: 'Rainbow Flag', category: 'flags', keywords: ['pride', 'lgbtq'] },
  { emoji: '🇺🇸', name: 'Flag: United States', category: 'flags', keywords: ['usa', 'america'] },
  { emoji: '🇬🇧', name: 'Flag: United Kingdom', category: 'flags', keywords: ['uk', 'britain'] },
  { emoji: '🇨🇦', name: 'Flag: Canada', category: 'flags', keywords: ['maple leaf'] },
  { emoji: '🇯🇵', name: 'Flag: Japan', category: 'flags', keywords: ['nihon'] },
  { emoji: '🇩🇪', name: 'Flag: Germany', category: 'flags', keywords: ['deutschland'] },
  { emoji: '🇫🇷', name: 'Flag: France', category: 'flags', keywords: ['paris'] },
  { emoji: '🇮🇳', name: 'Flag: India', category: 'flags', keywords: ['bharat'] },
  { emoji: '🇦🇺', name: 'Flag: Australia', category: 'flags', keywords: ['aussie'] },
  { emoji: '🇧🇷', name: 'Flag: Brazil', category: 'flags', keywords: ['brasil'] },
];

export const GESTURE_DEFINITIONS = [
  { id: 'Thumb_Up', name: 'Thumbs Up', emoji: '👍', description: 'Make a fist with thumb pointing upward' },
  { id: 'Victory', name: 'Peace / Victory', emoji: '✌️', description: 'Extend index and middle fingers in a V' },
  { id: 'Open_Palm', name: 'Open Palm', emoji: '✋', description: 'Extend all five fingers flat toward camera' },
  { id: 'Closed_Fist', name: 'Closed Fist', emoji: '✊', description: 'Curl all fingers tightly into your palm' },
  { id: 'Pointing_Up', name: 'Pointing Up', emoji: '☝️', description: 'Extend index finger up with others curled' },
  { id: 'Thumb_Down', name: 'Thumbs Down', emoji: '👎', description: 'Make a fist with thumb pointing downward' },
  // Custom Landmark Rules:
  { id: 'OK_Sign', name: 'OK Sign', emoji: '👌', description: 'Touch thumb tip to index tip, middle/ring/pinky up' },
  { id: 'Love_You', name: 'I Love You', emoji: '🤟', description: 'Extend thumb, index, and pinky; fold middle & ring' },
  { id: 'Crossed_Fingers', name: 'Crossed Fingers', emoji: '🤞', description: 'Cross index and middle finger for good luck' },
  { id: 'Finger_Heart', name: 'Finger Heart', emoji: '🫰', description: 'Cross thumb and index tips into a tiny heart shape' },
  // Multi-hand & Mudras:
  { id: 'Namaste', name: 'Namaste / Pranam', emoji: '🙏', description: 'Join both palms and fingers flat together pointing upward in respect and greeting' },
  { id: 'Lotus_Flower', name: 'Lotus Flower / Kamal', emoji: '🪷', description: 'Join wrists together and open all fingers outward like blooming lotus petals' },
  { id: 'Rose_Flower', name: 'Rose / Flower Bud', emoji: '🌸', description: 'Gather all five fingertips closely together facing the camera like a flower bud' },
  { id: 'Two_Hand_Heart', name: 'Two-Hand Heart', emoji: '❤️', description: 'Touch both thumbs together and both index tips together' },
  { id: 'Clapping', name: 'Clapping Hands', emoji: '👏', description: 'Bring both open palms together in front of camera' },
  // Face Expressions:
  { id: 'Smile', name: 'Smile', emoji: '😀', description: 'Smile showing teeth or wide lips' },
  { id: 'Laugh', name: 'Big Laugh', emoji: '😆', description: 'Wide smile with squinting eyes' },
  { id: 'Surprise', name: 'Surprise', emoji: '😮', description: 'Drop jaw open and widen eyes' },
  { id: 'Scream', name: 'Screaming Shock', emoji: '😱', description: 'Wide open mouth with shock' },
  { id: 'Wink', name: 'Wink', emoji: '😉', description: 'Blink one eye while keeping the other open' },
  { id: 'Tongue', name: 'Stick Out Tongue', emoji: '😛', description: 'Stick your tongue out playfully' },
  { id: 'Wink_Tongue', name: 'Winking Tongue', emoji: '😜', description: 'Wink one eye while sticking your tongue out' },
  { id: 'Sad', name: 'Sad / Frown', emoji: '😢', description: 'Pull corners of mouth down into a frown' },
  { id: 'Angry', name: 'Angry', emoji: '😠', description: 'Furrow your eyebrows together downward' },
  { id: 'Skeptical', name: 'Raised Eyebrow', emoji: '🤨', description: 'Raise one eyebrow skeptically' },
  { id: 'Kiss', name: 'Kiss / Whistle', emoji: '😚', description: 'Pucker your lips forward' },
  { id: 'Wide_Eyes', name: 'Wide Eyes / Flushed', emoji: '😳', description: 'Open both eyes very wide' },
  { id: 'Sleepy', name: 'Sleepy Eyes', emoji: '😴', description: 'Close both eyes relaxed' },
  { id: 'Eye_Roll', name: 'Eye Roll', emoji: '🙄', description: 'Look eyes upward' },
  { id: 'Yawn', name: 'Yawn', emoji: '🥱', description: 'Open mouth wide while squinting' },
  { id: 'Shush', name: 'Sealed Lips', emoji: '🤐', description: 'Press lips tightly together' },
];

export const GESTURE_TO_EMOJI: Record<string, string> = {
  Thumb_Up: '👍',
  Thumb_Down: '👎',
  Victory: '✌️',
  Open_Palm: '✋',
  Closed_Fist: '✊',
  Pointing_Up: '☝️',
  ILoveYou: '🤟',
  OK_Sign: '👌',
  Love_You: '🤟',
  Crossed_Fingers: '🤞',
  Finger_Heart: '🫰',
  Two_Hand_Heart: '❤️',
  Clapping: '👏',
  Thinking: '🤔',
  Namaste: '🙏',
  Pranam: '🙏',
  Lotus_Flower: '🪷',
  Rose_Flower: '🌸',
  Flower_Bloom: '🌸',
  // Face Expressions:
  Smile: '😀',
  Laugh: '😆',
  Surprise: '😮',
  Scream: '😱',
  Wink: '😉',
  Tongue: '😛',
  Wink_Tongue: '😜',
  Sad: '😢',
  Angry: '😠',
  Skeptical: '🤨',
  Kiss: '😚',
  Wide_Eyes: '😳',
  Sleepy: '😴',
  Eye_Roll: '🙄',
  Yawn: '🥱',
  Shush: '🤐',
};

const CUSTOM_EMOJI_STORAGE_KEY = 'gesturemoji_custom_emojis';

export function getCustomEmojis(): EmojiItem[] {
  try {
    const saved = localStorage.getItem(CUSTOM_EMOJI_STORAGE_KEY);
    return saved ? JSON.parse(saved) : [];
  } catch {
    return [];
  }
}

export function addCustomEmojiItem(item: EmojiItem): EmojiItem[] {
  const current = getCustomEmojis();
  const exists = current.some((e) => e.emoji === item.emoji);
  if (exists) return current;

  const updated = [item, ...current];
  try {
    localStorage.setItem(CUSTOM_EMOJI_STORAGE_KEY, JSON.stringify(updated));
  } catch (e) {
    console.warn('Could not save custom emoji to localStorage', e);
  }
  return updated;
}

export function getAllEmojisWithCustom(): EmojiItem[] {
  const custom = getCustomEmojis();
  return [...custom, ...ALL_EMOJIS];
}

